In [19]:
import numpy as np
np.random.seed(0)
import matplotlib.pyplot as plt
%matplotlib inline

## Using Gaussian NB

In [26]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y) #ml.splitData(X, y, 0.70)

model = GaussianNB()

model.fit(X_train,y_train)
print(model)

predict = model.predict(X_test)

print(metrics.classification_report(y_test,predict))
print(metrics.confusion_matrix(y_test,predict))

GaussianNB(priors=None)
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       0.85      0.92      0.88        12
          2       0.92      0.85      0.88        13

avg / total       0.92      0.92      0.92        38

[[13  0  0]
 [ 0 11  1]
 [ 0  2 11]]
