In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
%%time 
2 ** 1000

CPU times: user 11 µs, sys: 1 µs, total: 12 µs
Wall time: 22.4 µs


10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [3]:
import numpy as np

In [4]:
np.int64(2) ** 1000

0

In [5]:
%%time 

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [7]:
%%time
np.int64(2) ** 1000

CPU times: user 12 µs, sys: 7 µs, total: 19 µs
Wall time: 22.2 µs


0

In [8]:
arr = np.array([1,2,3])

In [9]:
len(arr)

3

In [10]:
arr[1]

2

In [11]:
type(arr[1])

numpy.int64

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr32 = np.array([1,2,3], dtype=np.int32)

In [14]:
arr32

array([1, 2, 3], dtype=int32)

In [15]:
arr * arr

array([1, 4, 9])

In [16]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [17]:
%time v1*v2


CPU times: user 4.34 ms, sys: 2.02 ms, total: 6.35 ms
Wall time: 5.55 ms


array([0.32503959, 0.09475271, 0.14242806, ..., 0.79688486, 0.58735417,
       0.04291618])

In [18]:
arr @ arr


14

In [19]:
np.dot(arr,arr
      )

14

In [20]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
vp = np.arange(12)
vp


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
v.reshape([4,3])

NameError: name 'v' is not defined

In [23]:
vp.reshape([4,3
           ])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
mat2 = mat.reshape([3,4])

ValueError: cannot reshape array of size 9 into shape (3,4)

In [25]:
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
mat2 = vp.reshape([3,4])

In [27]:
mat2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
mat2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
nums = [1,2,3,4,5]
nums[2:4]

[3, 4]

In [30]:
arr[:,1
   ]

IndexError: too many indices for array

In [31]:
arr

array([1, 2, 3])

In [32]:
mat2[:,1]

array([1, 5, 9])

In [33]:
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
mat2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [35]:
mat2[0:,0:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
arr


array([1, 2, 3])

In [38]:
arr >= 1

array([ True,  True,  True])

In [39]:
arr > 1

array([False,  True,  True])

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr